/* eslint-disable */
export const categories = [
    {
        id: '9a67dff7-3c38-4052-a335-0cef93438ff6',
        title: 'Buy Necessity',
        slug: 'buy-necessity'
    },
    {
        id: 'a89672f5-e00d-4be4-9194-cb9d29f82165',
        title: 'Send Document',
        slug: 'send-document'
    },
    {
        id: '02f42092-bb23-4552-9ddb-cfdcc235d48f',
        title: 'Food Delivery',
        slug: 'food-delivery'
    },
    {
        id: '5648a630-979f-4403-8c41-fc9790dea8cd',
        title: 'Other',
        slug: 'other'
    }
];
export const tasks = [
    {
        id: '694e4e5f-f25f-470b-bd0e-26b1d4f64028',
        title: 'Buy Coke',
        description: '2 cans of coke need chilled',
        category: 'buy-necessity',
        from: 'other',
        to: 'Woodlands',
        date: '2021/6/22',
        time: '13:45',
        expectedRate: 10,
        agreedRate: 0,
        duration: 30,
        currentStep: 2,
        assignedUserId: 'aA',
        taskOwnerId: 'owner1',
    },
    {
        id: 'f924007a-2ee9-470b-a316-8d21ed78277f',
        title: 'Buy Beer',
        description: 'Two bottles of tiger beer',
        category: 'buy-necessity',
        from: 'other',
        to: 'Woodlands',
        date: '2021/7/22',
        time: '19:33',
        expectedRate: 20,
        agreedRate: 0,
        duration: 15,
        currentStep: 1,
        assignedUserId: 'b',
        taskOwnerId: 'owner2',
    },
    {
        id: '0c06e980-abb5-4ba7-ab65-99a228cab36b',
        title: 'Wash car',
        description: 'Wash car in the car park',
        category: 'other',
        from: 'other',
        to: 'Tai Seng',
        date: '2021/9/21',
        time: '19:33',
        expectedRate: 15,
        agreedRate: 0,
        duration: 15,
        currentStep: 0,
        assignedUserId: '',
        taskOwnerId: 'owner3',
    },
    {
        id: '1b9a9acc-9a36-403e-a1e7-b11780179e38',
        title: 'Send package',
        description: 'Send document to client office',
        category: 'send-document',
        from: 'Admiralty',
        to: 'Jurong East',
        date: '2021/7/21',
        time: '8:20',
        expectedRate: 10,
        agreedRate: 0,
        duration: 30,
        currentStep: 0,
        assignedUserId: '',
        taskOwnerId: 'owner4',
    },
    {
        id: '55eb415f-3f4e-4853-a22b-f0ae91331169',
        title: 'Walk my pet',
        description: 'Nobody at home tonight till late, the pet needs accompany',
        category: 'other',
        from: 'Other',
        to: 'Toa Payoh',
        date: '2021/7/2',
        time: '19:00',
        expectedRate: 15,
        agreedRate: 0,
        duration: 30,
        currentStep: 0,
        assignedUserId: '',
        taskOwnerId: 'owner5',
    },
    {
        id: 'fad2ab23-1011-4028-9a54-e52179ac4a50',
        title: 'Buy burger',
        description: 'Deliver chicken burger to home',
        category: 'food-delivery',
        from: 'Mcdonalds',
        to: 'Hougang',
        date: '2021/7/2',
        time: '16:00',
        expectedRate: 10,
        agreedRate: 0,
        duration: 30,
        currentStep: 0,
        assignedUserId: '',
        taskOwnerId: 'owner5',
    },
    {
        id: 'c4bc107b-edc4-47a7-a7a8-4fb09732e794',
        title: 'Buy beer',
        description: 'Two bottles of beer to home',
        category: 'buy-necessity',
        from: '7-11',
        to: 'Bedok',
        date: '2021/6/29',
        time: '19:30',
        expectedRate: 11,
        agreedRate: 0,
        duration: 30,
        currentStep: 0,
        assignedUserId: '',
        taskOwnerId: 'owner6',
    },
    {
        id: '1449f945-d032-460d-98e3-406565a22293',
        title: 'Send receipt',
        description: 'Send receipt to client',
        category: 'send-document',
        from: 'Novena',
        to: 'City Hall',
        date: '2021/6/29',
        time: '10:30',
        expectedRate: 10,
        agreedRate: 0,
        duration: 15,
        currentStep: 0,
        assignedUserId: '',
        taskOwnerId: 'owner7',
    },
    {
        id: 'f05e08ab-f3e3-4597-a032-6a4b69816f24',
        title: 'Buy chicken rice',
        description: 'Buy one set of chicken and deliver to home',
        category: 'food-delivery',
        from: 'Food court',
        to: 'Holland Village',
        date: '2021/6/29',
        time: '12:30',
        expectedRate: 10,
        agreedRate: 0,
        duration: 15,
        currentStep: 0,
        assignedUserId: '',
        taskOwnerId: 'owner8',
    },
    {
        id: '181728f4-87c8-45c5-b9cc-92265bcd2f4d',
        title: 'Buy fried rice',
        description: 'Buy two bowls of fried rice',
        category: 'food-delivery',
        from: 'Food court',
        to: 'Jurong West',
        date: '2021/6/29',
        time: '12:30',
        expectedRate: 15,
        agreedRate: 0,
        duration: 15,
        currentStep: 0,
        assignedUserId: '',
        taskOwnerId: 'owner9',
    },
    {
        id: 'fcbfedbf-6187-4b3b-89d3-1a7cb4e11616',
        title: 'Send contract',
        description: 'Send contract document to client',
        category: 'send-document',
        from: 'Outram Park',
        to: 'Telok Ayer',
        date: '2021/6/26',
        time: '14:30',
        expectedRate: 15,
        agreedRate: 0,
        duration: 15,
        currentStep: 0,
        assignedUserId: '',
        taskOwnerId: 'owner10',
    },
    {
        id: '5213f6a1-1dd7-4b1d-b6e9-ffb7af534f28',
        title: 'Buy cooking oil',
        description: 'Get one bottle of cooking oil 500ml',
        category: 'buy-necessity',
        from: 'Fair Price',
        to: 'Woodlands',
        date: '2021/6/26',
        time: '9:30',
        expectedRate: 15,
        agreedRate: 0,
        duration: 15,
        currentStep: 0,
        assignedUserId: '',
        taskOwnerId: 'owner11',
    },
    {
        id: '02992ac9-d1a3-4167-b70e-8a1d5b5ba253',
        title: 'Buy veges',
        description: 'Buy 500g veges from market',
        category: 'buy-necessity',
        from: 'Market',
        to: 'Braddell',
        date: '2021/6/27',
        time: '9:30',
        expectedRate: 15,
        agreedRate: 0,
        duration: 15,
        currentStep: 0,
        assignedUserId: '',
        taskOwnerId: 'owner12',
    },
    {
        id: '2139512f-41fb-4a4a-841a-0b4ac034f9b4',
        title: 'Play badminton',
        description: 'Form a team and play badminton',
        category: 'other',
        from: 'other',
        to: 'Sports hall',
        date: '2021/6/27',
        time: '19:30',
        expectedRate: 15,
        agreedRate: 0,
        duration: 15,
        currentStep: 0,
        assignedUserId: '',
        taskOwnerId: 'owner13',
    },
];
export const demoTaskIssuedContent = `
Task Issued
`;
export const demoTaskExecutionContent = `
Task Executing
`;
export const demoTaskCompleteContent = `
Task Complete
`;
export const taskSteps = [
    {
        order: 0,
        title: 'Task Issued',
        subTitle: `Task is issued! Now the task description is available!`,
        content: `<h2 class="text-2xl sm:text-3xl">Task Issued</h1>
<h3>Description</h3>
${demoTaskIssuedContent}
`
    },
    {
        order: 1,
        title: 'Task Execution',
        subTitle: `Task is in execution stage! Complete before due time to avoid penalty.`,
        content: `<h2 class="text-2xl sm:text-3xl">Task Execution</h1>${demoTaskExecutionContent}`
    },
    {
        order: 2,
        title: 'Task Complete',
        subTitle: `Task is complete.`,
        content: `<h2 class="text-2xl sm:text-3xl">Task Complete</h1>${demoTaskCompleteContent}`
    },
];
